sudo: required
services:
    - docker

before_install:
    - docker build -t docker-react -f Dockerfile.test .

script:
    - docker run docker-react

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'docker-react'
    env: 'DockerReact-env'
    bucket_name: 'elasticbeanstalk-us-east-2-554464796576'
    bucket_path: 'docker-react'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: '$AWS_SECRET_KEY'
